### ISSUE TITLE
cf-remote fails if curl is not installed

### ISSUE THREAD

**Issue by MasinAD** [cfengine/cf-remote#88]
I finally came to trying `cf-remote`.

```
[masin.wiedner@toolbox ~]$ cf-remote install --edition community --hub root@gamma --clients root@gamma --remote-download

root@gamma
OS            : Debian 11
Architecture  : x86_64
CFEngine      : Not installed
Policy server : None
Binaries      : dpkg, apt

Downloading 'https://cfengine-package-repos.s3.amazonaws.com/community_binaries/Community-3.21.4/agent_debian11_x86_64/cfengine-community_3.21.4-1.debian11_amd64.deb' on 'root@gamma' using curl

bash: line 1: curl: command not found

[ERROR] Non-sudo command unexpectedly exited: 'curl --fail -O https://cfengine-package-repos.s3.amazonaws.com/community_binaries/Community-3.21.4/agent_debian11_x86_64/cfengine-community_3.21.4-1.debian11_amd64.deb' [127]
[ERROR] 1 error encountered while installing hub packages, aborting...
```

I am still trying to figure out what `--hub`, `--clients` and `--bootstrap` mean in this context, but this is not part of this issue. I'd suggest, `cf-remote` should check for availability of `curl` before downloading the package and install `curl` before attempting to use it.

**Comment by olehermanse** [comment]
Good point. I've created a ticket to fix it:

https://northerntech.atlassian.net/browse/CFE-4405

See my response in the other GH discussions thread when it comes to `--hub`, etc.:

https://github.com/cfengine/core/discussions/5545
